export './aboutus_view.dart';
export './analysis_view.dart';
export './contact_view.dart';
export './feedback_view.dart';
export './policy_view.dart';
export './profile_view.dart'; 
export './recorded_videos_view.dart';
export './today_lecture_view.dart';
export './upcoming_lecture_view.dart';
